### ISSUE TITLE
pdf.loadFromJSON(serializedJSON) not working

### ISSUE THREAD

**Issue by janlord01** [RavishaHesh/PDFJsAnnotations#53]
Tried to load pdf.loadFromJSON(serializedJSON) but its not working. Any help please? Thanks

**Comment by RavishaHesh** [comment]
Are there any errors in the browser's dev tool console? like JSON parse errors

**Comment by janlord01** [comment]
> Are there any errors in the browser's dev tool console? like JSON parse errors

no errors on ready(), but when I console log it, it outputs undefined.

**Comment by str** [comment]
@janlord01 could you please paste your code to better understand your issue?

**Comment by khaledmndev** [comment]
i'm having an issue while retrieving json data from the storage after parsing it 

here's my code: 
```
 var data1 = JSON.parse(localStorage.getItem('CanvaData'));
 pdf.loadFromJSON(data1)
```

any solution?

**Comment by str** [comment]
@khaledmndev and can you post your data1 value?

**Comment by khaledmndev** [comment]
> @khaledmndev and can you post your data1 value?

sure, i used console.log(data1) if you that i you wanted:

here's a link for the value stored in a txt file, since the value and size is too big (sorry can't paste it here): 
[https://mega.nz/file/q9ZmxRZb#qJPj3mB8MQzG34UWf53zPRbO960XsdVnRdS9RzluGeY](https://mega.nz/file/q9ZmxRZb#qJPj3mB8MQzG34UWf53zPRbO960XsdVnRdS9RzluGeY)

**Comment by str** [comment]
@khaledmndev and what error message do you get?

**Comment by khaledmndev** [comment]
> @khaledmndev and what error message do you get?
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at i.loadFromJSON (fabric.min.js:1:131008)
    at i.<anonymous> (pdfannotate.js:286:14)
    at Function.each (jquery.min.js:2:2976)
    at PDFAnnotate.loadFromJSON (pdfannotate.js:284:4)
    at Object.ready (script.js:15:13)
    at HTMLCanvasElement.<anonymous> (pdfannotate.js:87:13)
    at Function.each (jquery.min.js:2:2976)
    at S.fn.init.each (jquery.min.js:2:1454)
    at PDFAnnotate.initFabric (pdfannotate.js:60:15)

**Comment by khaledmndev** [comment]
@str 
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
at JSON.parse ()
at i.loadFromJSON (fabric.min.js:1:131008)
at i. (pdfannotate.js:286:14)
at Function.each (jquery.min.js:2:2976)
at PDFAnnotate.loadFromJSON (pdfannotate.js:284:4)
at Object.ready (script.js:15:13)
at HTMLCanvasElement. (pdfannotate.js:87:13)
at Function.each (jquery.min.js:2:2976)
at S.fn.init.each (jquery.min.js:2:1454)
at PDFAnnotate.initFabric (pdfannotate.js:60:15)

**Comment by str** [comment]
@khaledmndev as you can see, the error says it was not able to parse the JSON value (1.5MB string length). It may be because of the length of the background fields in the canvas.  I  suggest you to try without the backgrounds

If you still get any errors, I suggest you to open a new issue with that error message.

**Comment by khaledmndev** [comment]
@str still no luck i've tried with only drawing with pen!
i'll open a new issue..

by the way i tried pasting the json value data into pdf.loadFromJSON("here"), and it worked!
thanks for helping anyways :)

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ output annotations : output annotations for importing;
④ import annotations : import annotations for current file;
⑤ download annotations : download annotations and comments text;
⑥ undo annotations : undo annotations in current page;
⑦ help : open help file;
